# Generated by Django 5.1.2 on 2024-10-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_alter_player_daily_login_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='daily_login_streak',
            field=models.IntegerField(null=True),
        ),
    ]
